
CREATE OR REPLACE  VIEW V_SERVICE
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'SERVICE'
;

CREATE OR REPLACE  VIEW V_PROCESSUS_STAGE
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'PROCESSUS_STAGE'
;

CREATE OR REPLACE  VIEW V_DOMAINE_ACTIVITE
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'DOMAINE_ACTIVITE'
;

CREATE OR REPLACE  VIEW V_SEMESTRE
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'SEMESTRE'
;

CREATE OR REPLACE  VIEW V_DIPLOME
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'DIPLOME'
;

CREATE OR REPLACE  VIEW V_TYPE_EMPLOI
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'TYPE_EMPLOI'
;

CREATE OR REPLACE  VIEW V_FONCTION
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'FONCTION'
;

CREATE OR REPLACE  VIEW V_MOYEN_OBTENTION_EMPLOI
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'MOYEN_OBTENTION_EMPLOI'
;

CREATE OR REPLACE  VIEW V_OUI_NON
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'OUI_NON'
;

