--
-- Structure de la table `question_evaluation`
--

CREATE TABLE IF NOT EXISTS `question_evaluation` (
  `ID_QUESTION_EVALUATION` mediumint(9) NOT NULL AUTO_INCREMENT,
  `ID_RUBRIQUE_EVALUATION` mediumint(9) DEFAULT NULL,
  `ID_QUESTION` mediumint(9) DEFAULT NULL,
  `ID_QUALIFICATIF` mediumint(9) DEFAULT NULL,
  `ORDRE` decimal(2,0) DEFAULT NULL,
  `INTITULE` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID_QUESTION_EVALUATION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1 ;

--
-- Structure de la table `evaluation`
--

CREATE TABLE IF NOT EXISTS `evaluation` (
  `ID_EVALUATION` mediumint(9) NOT NULL AUTO_INCREMENT,
  `NO_ENSEIGNANT` decimal(5,0) DEFAULT NULL,
  `CODE_FORMATION` varchar(8) COLLATE utf8_bin DEFAULT NULL,
  `ANNEE_PRO` varchar(10) COLLATE utf8_bin DEFAULT NULL,
  `CODE_UE` varchar(8) COLLATE utf8_bin DEFAULT NULL,
  `CODE_EC` varchar(8) COLLATE utf8_bin DEFAULT NULL,
  `NO_EVALUATION` decimal(2,0) DEFAULT NULL,
  `DESIGNATION` varchar(300) COLLATE utf8_bin DEFAULT NULL,
  `ETAT` varchar(3) COLLATE utf8_bin DEFAULT NULL,
  `PERIODE` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `DEBUT_REPONSE` datetime DEFAULT NULL,
  `FIN_REPONSE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_EVALUATION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1 ;


--
-- Structure de la table `rubrique`
--

CREATE TABLE IF NOT EXISTS `rubrique` (
  `ID_RUBRIQUE` mediumint(9) NOT NULL AUTO_INCREMENT,
  `TYPE` varchar(10) COLLATE utf8_bin DEFAULT NULL,
  `DESIGNATION` varchar(32) COLLATE utf8_bin DEFAULT NULL,
  `ORDRE` double DEFAULT NULL,
  `NO_ENSEIGNANT` decimal(5,0) DEFAULT NULL,
  PRIMARY KEY (`ID_RUBRIQUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1 ;


--
-- Structure de la table `rubrique_question`
--

CREATE TABLE  `rubrique_question` (
  `ID_RUBRIQUE` MEDIUMINT,
  `ID_QUESTION` MEDIUMINT,
  `ORDRE` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--
-- Structure de la table `rubrique_evaluation`
--

CREATE TABLE IF NOT EXISTS `rubrique_evaluation` (
  `ID_RUBRIQUE_EVALUATION` mediumint(9) NOT NULL AUTO_INCREMENT,
  `ID_EVALUATION` mediumint(9) DEFAULT NULL,
  `ID_RUBRIQUE` mediumint(9) DEFAULT NULL,
  `ORDRE` decimal(2,0) DEFAULT NULL,
  `DESIGNATION` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID_RUBRIQUE_EVALUATION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1 ;


--
-- Structure de la table `qualificatif`
--

CREATE TABLE IF NOT EXISTS `qualificatif` (
  `ID_QUALIFICATIF` mediumint(9) NOT NULL AUTO_INCREMENT,
  `MAXIMAL` varchar(16) COLLATE utf8_bin DEFAULT NULL,
  `MINIMAL` varchar(16) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID_QUALIFICATIF`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1 ;


--
-- Structure de la table `droit`
--

CREATE TABLE  `droit` (
  `ID_EVALUATION` MEDIUMINT,
  `NO_ENSEIGNANT` decimal(5,0) DEFAULT NULL,
  `CONSULTATION` varchar(1) COLLATE utf8_bin DEFAULT NULL,
  `DUPLICATION` varchar(1) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (ID_EVALUATION,NO_ENSEIGNANT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


--
-- Structure de la table `question`
--

CREATE TABLE IF NOT EXISTS `question` (
  `ID_QUESTION` mediumint(9) NOT NULL AUTO_INCREMENT,
  `TYPE` varchar(10) COLLATE utf8_bin DEFAULT NULL,
  `NO_ENSEIGNANT` decimal(5,0) DEFAULT NULL,
  `ID_QUALIFICATIF` mediumint(9) DEFAULT NULL,
  `INTITULE` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID_QUESTION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1 ;

--
-- Structure de la table `reponse_question`
--

CREATE TABLE  `reponse_question` (
  `ID_REPONSE_QUESTION` MEDIUMINT,
  `ID_QUESTION_EVALUATION` MEDIUMINT,
  `POSITIONNEMENT` double DEFAULT NULL,
  PRIMARY KEY (ID_REPONSE_QUESTION,ID_QUESTION_EVALUATION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


--
-- Structure de la table `reponse_evaluation`
--

CREATE TABLE  `reponse_evaluation` (
  `ID_REPONSE_EVALUATION` MEDIUMINT,
  `ID_EVALUATION` MEDIUMINT,
  `NO_ETUDIANT_NAT` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `COMMENTAIRE` varchar(512) COLLATE utf8_bin DEFAULT NULL,
  `NOM` varchar(32) COLLATE utf8_bin DEFAULT NULL,
  `PRENOM` varchar(32) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (ID_REPONSE_EVALUATION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

