
CREATE OR REPLACE  VIEW V_POSITIONNEMENT
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE RV_DOMAIN='POSITIONNEMENT'
;

CREATE OR REPLACE  VIEW V_ETAT_EVALUATION
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE RV_DOMAIN='ETAT_EVALUATION'
;

CREATE OR REPLACE  VIEW V_QUESTION
 (QEV_ORDRE
 ,QEV_INTITULE
 ,QUA_MINIMAL
 ,QUA_MAXIMAL)
 AS SELECT QEV.ORDRE QEV_ORDRE
          ,QEV.INTITULE QEV_INTITULE
          ,QUA.MINIMAL QUA_MINIMAL
          ,QUA.MAXIMAL QUA_MAXIMAL
FROM QUESTION_EVALUATION QEV
    ,QUALIFICATIF QUA
  WHERE QUA.ID_QUALIFICATIF = QEV.ID_QUALIFICATIF
;

CREATE OR REPLACE  VIEW V_QUESTION_S
 (QUE_INTITULE
 ,QUA_MINIMAL
 ,QUA_MAXIMAL)
 AS SELECT QUE.INTITULE QUE_INTITULE
          ,QUA.MINIMAL QUA_MINIMAL
          ,QUA.MAXIMAL QUA_MAXIMAL
FROM QUESTION QUE
    ,QUALIFICATIF QUA
  WHERE QUE.ID_QUALIFICATIF = QUA.ID_QUALIFICATIF
;

CREATE OR REPLACE  VIEW V_EVALUATION
 (EVE_ANNEE_PRO
 ,FRM_CODE_FORMATION
 ,EVE_PERIODE
 ,EVE_DESIGNATION
 ,EVE_ETAT
 ,EVE_ID_EVALUATION
 ,UE_DESIGNATION
 ,ENS_NOM)
 AS SELECT EVE.ANNEE_PRO EVE_ANNEE_PRO
          ,FRM.CODE_FORMATION FRM_CODE_FORMATION
          ,EVE.PERIODE EVE_PERIODE
          ,EVE.DESIGNATION EVE_DESIGNATION
          ,EVE.ETAT EVE_ETAT
		  ,EVE.ID_EVALUATION EVE_ID_EVALUATION
          ,UE.DESIGNATION UE_DESIGNATION
          ,ENS.NOM ENS_NOM
FROM ENSEIGNANT ENS
    ,EVALUATION EVE
    ,FORMATION FRM
    ,PROMOTION PRO
    ,UNITE_ENSEIGNEMENT UE
  WHERE EVE.NO_ENSEIGNANT=ENS.NO_ENSEIGNANT AND EVE.ANNEE_PRO=PRO.ANNEE_PRO AND PRO.CODE_FORMATION=FRM.CODE_FORMATION AND UE.CODE_UE = EVE.CODE_UE
;

CREATE VIEW V_RUBEVAL
(EVE_ID_EVALUATION
 ,ENS_NOM
 ,REV_ORDRE
 ,REV_DESIGNATION)
AS SELECT EVE.ID_EVALUATION EVE_ID_EVALUATION
			, ENS.NOM ENS_NOM
			, REV.ORDRE REV_ORDRE
			, REV.DESIGNATION REV_DESIGNATION
FROM EVALUATION EVE
	,RUBRIQUE_EVALUATION REV
	,ENSEIGNANT ENS
WHERE EVE.ID_EVALUATION = REV.ID_EVALUATION AND EVE.NO_ENSEIGNANT=ENS.NO_ENSEIGNANT
;
